/* Copyright 2026 上海如静知华信息科技有限公司 */
export const domain={
 code:'AGENTSEC',systemName:'知华 AgentSec',englishName:'AI AGENT SECURITY LAB',theme:{primary:'#a3473e',dark:'#2d292c',accent:'#d08b42'},workspace:'AI 安全实验室 / Agent 红队',fieldWorkspace:'Agent 红队组',period:'2026-08-02 · 测试窗口',liveText:'攻击轨迹于 10:44 更新',fieldContextLabel:'当前测试环境',fieldContext:'隔离区 · Release 8',fieldUser:'陆遥',fieldRole:'Agent 安全测试员',adminUser:'何谨',adminRole:'AI 安全负责人',adminTitle:'Agent 安全测试与发布门禁',adminBreadcrumb:'AgentSec / 安全态势',adminSubtitle:'围绕提示注入、工具越权、凭证泄漏、记忆污染和沙箱逃逸开展可复现安全测试。',exportAction:'生成红队报告',createAction:'启动攻击演练',chartTitle:'攻击用例覆盖趋势',chartSubtitle:'实际覆盖率 / 发布门禁目标',chartLabels:['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00'],loadTitle:'测试面覆盖负荷',loadSubtitle:'开放用例占测试环境容量',recordsTitle:'重点 Agent 测试任务',recordsSubtitle:'按影响等级、工具权限与发布窗口排序',issueTitle:'阻断级安全发现',issueSubtitle:'必须在发布前修复或接受风险的事项',recordName:'测试任务',itemName:'Agent',unitName:'测试团队',batchName:'影响等级',planName:'用例',doneName:'已执行',exceptionName:'发现',unitLabel:'项',listBreadcrumb:'安全验证 / 测试中心',listSubtitle:'管理威胁建模、攻击用例、轨迹复现、修复验证和发布门禁。',listSummary:[['在测 Agent','18'],['攻击用例','326'],['本周发现','27'],['阻断发布','4',true]],tabs:['全部','待测试','执行中','待复测','已验收'],fieldBreadcrumb:'AgentSec / 测试员工作台',fieldTitle:'Agent 红队测试工作台',fieldSubtitle:'当前 7 个测试任务 · 4 个阻断级发现 · 测试员陆遥',fieldSecondary:'查看测试排期',reportAction:'提交测试发现',fieldNoticeTitle:'隔离测试环境运行正常',fieldNotice:'工具调用、模型输入输出和记忆写入轨迹覆盖率 97.4%',steps:['威胁建模','用例准备','攻击执行','修复复测','发布决策'],documentAction:'查看测试手册',printAction:'导出复现包',resourceCardTitle:'安全测试设施',resourceValueLabel:'攻击用例',resourceHealthLabel:'轨迹完整率',quickSubtitle:'测试员常用入口',quickActions:[['测试发现','/shopfloor/report','复现、影响和修复建议'],['用例库','/shopfloor/material','提示、工具和记忆攻击'],['实验环境','/shopfloor/resources','沙箱、探针和轨迹采集'],['风险升级','/shopfloor/andon','阻断发布和风险接受']],reportDefaults:[6,1],reportTitle:'Agent 安全测试发现',reportSubtitle:'记录已执行用例、有效发现和复现说明。',reportSuccess:'测试发现已写入安全轨迹',reportPlaceholder:'填写攻击载荷摘要、复现步骤、影响范围和修复建议',reportFootnote:'请勿在报告中保存真实密钥或生产敏感数据',ruleTitle:'Agent 发布安全门禁',ruleSubtitle:'AGENT-SEC · V2.0',rules:[['高风险工具','人工审批'],['执行环境','强制沙箱'],['敏感凭证','短期范围化'],['阻断级发现','必须清零',true]],fieldTotals:[['18','在测 Agent'],['326','攻击用例'],['27','本周发现'],['97.4%','轨迹完整率']],
 adminMenus:[['/admin','home','安全测试中心'],['/admin/work-orders','order','测试任务'],['/admin/samples','box','Agent 资产'],['/admin/schedule','calendar','测试排期'],['/admin/methods','process','攻击用例库'],['/admin/reviews','quality','修复复测'],['/admin/resources','machine','实验环境'],['/admin/report','chart','风险分析']],fieldMenus:[['/shopfloor','home','测试员工作台'],['/shopfloor/report','report','测试发现'],['/shopfloor/tasks','order','我的任务'],['/shopfloor/material','box','攻击用例'],['/shopfloor/resources','machine','实验环境'],['/shopfloor/andon','risk','风险升级',4]],moduleTitles:{tasks:['我的测试任务','查看威胁模型、用例进度和发布期限'],material:['攻击用例库','检索提示注入、工具越权、记忆污染和数据泄漏用例'],resources:['隔离实验环境','查看沙箱、探针、模型代理和轨迹采集'],andon:['风险升级','提交阻断发布或风险接受审批'],samples:['Agent 资产','登记模型、工具、权限、记忆和部署环境'],schedule:['测试排期','协调环境、测试人和发布窗口'],methods:['攻击用例库','维护攻击载荷、预期行为和判定规则'],reviews:['修复复测','验证缓解措施和回归影响'],report:['风险分析','分析攻击面、发现趋势和修复时效']},tagline:'在 Agent 接触真实业务之前，先验证它的安全边界',storyTitle:'能力越自主，<br/>越要经得住真实攻击。',storyText:'面向企业 Agent 的威胁建模、红队演练、证据复现与发布门禁平台。',pattern:[1,3,6,8,11,14,16,19,22,25,28,31],loginStats:[['326','攻击用例'],['27','本周发现'],['4','阻断发布']],loginTitle:'Agent 安全测试与发布门禁',adminDemo:'资产 / 用例 / 门禁',fieldDemo:'攻击 / 复现 / 复测'
}
export const records=[{no:'RED-260801-018',name:'财务 Agent 越权工具攻击演练',code:'FINANCE-AGENT',unit:'Agent 红队组',group:'AI 安全实验室',plan:24,done:16,exception:3,due:'08-03',batch:'严重',status:'攻击执行',progress:67,priority:'加急'},{no:'RED-260801-021',name:'客服 Agent 提示注入回归',code:'SERVICE-AGENT',unit:'Agent 红队组',group:'AI 安全实验室',plan:18,done:8,exception:2,due:'08-04',batch:'高',status:'执行中',progress:48,priority:'关注'},{no:'RED-260802-006',name:'研发 Agent 沙箱逃逸验证',code:'DEV-AGENT',unit:'工具安全组',group:'应用安全中心',plan:12,done:0,exception:0,due:'08-05',batch:'严重',status:'待测试',progress:12,priority:'加急'},{no:'RED-260728-015',name:'招聘助手隐私泄漏复测',code:'HR-AGENT',unit:'评测与复现组',group:'质量工程部',plan:20,done:20,exception:1,due:'08-01',batch:'中',status:'已验收',progress:100,priority:'正常'},{no:'RED-260802-009',name:'销售 Agent 长期记忆污染测试',code:'SALES-AGENT',unit:'Agent 红队组',group:'AI 安全实验室',plan:16,done:11,exception:3,due:'08-04',batch:'高',status:'待复测',progress:73,priority:'关注'}]
export const resources=[{code:'LAB-INJECT-03',name:'提示注入用例库',unit:'AI 安全实验室',status:'在线',health:97,value:'326',valueUnit:'例',note:'覆盖直接与间接注入'},{code:'LAB-SANDBOX-02',name:'隔离工具执行池',unit:'应用安全中心',status:'在线',health:92,value:'24',valueUnit:'实例',note:'文件和网络权限按任务隔离'},{code:'LAB-TRACE-05',name:'Agent 轨迹采集器',unit:'质量工程部',status:'预警',health:79,value:'97.4%',valueUnit:'',note:'2 个记忆写入事件缺少来源'}]
export const reviews=[{no:'FIND-260801-032',title:'财务 Agent 转账工具越权',type:'阻断级发现',detail:'复现 6/6 · 何谨',result:'待确认'},{no:'FIND-260801-011',title:'客服 Agent 间接提示注入',type:'修复复测',detail:'18 个载荷 · 陆遥',result:'通过'},{no:'FIND-260728-018',title:'销售 Agent 记忆来源缺失',type:'持久化风险',detail:'影响 3 个会话',result:'异常'}]
export const adminMetrics=[['在测 Agent','18','覆盖 7 个业务域','blue'],['攻击用例','326','本周新增 28 个','green'],['有效安全发现','27','高危及以上 9 个','orange'],['阻断发布','4','均已指定修复人','red']]
export const fieldMetrics=[['我的测试任务','7','4 个高风险任务','blue'],['今日已执行','46','有效发现 8 个','green'],['待复测发现','12','5 项临近发布','orange'],['轨迹完整率','97.4%','目标 99%','slate']]
export const chartActual=[14,23,31,42,52,61,70,78,84],chartTarget=[18,28,38,48,58,68,78,88,96]
export const loads=[['提示注入与越狱',88,'开放用例 96 个'],['工具权限与副作用',82,'开放用例 74 个'],['数据与凭证泄漏',73,'开放用例 61 个'],['记忆与沙箱安全',66,'开放用例 48 个']]
export const issues=[{type:'越权',title:'财务 Agent 可绕过确认调用转账工具',detail:'严重风险 · 发布窗口 08-05',status:'阻断'},{type:'记忆',title:'销售 Agent 接受未标记来源的长期记忆',detail:'可跨会话影响后续决策',status:'待复测'},{type:'凭证',title:'研发 Agent 工具日志包含令牌片段',detail:'已完成日志脱敏修复',status:'验证中'}]
